### ISSUE TITLE
"directoru" spelling mistake

### ISSUE THREAD

**Issue by mstevens** [nohuhu/CGI-Test#6]
Was reading the docs prior to using it, noticed:

=item C<-cgi_dir> => I<path to the cgi-bin directoru>

Probably should say "directory" instead?

**Comment by nohuhu** [comment]
Fixed in https://github.com/nohuhu/CGI-Test/commit/37f1ad87fb035696d45e9dfb6c62f1dfa9b798e8, thanks for catching!
