### ISSUE TITLE
Different license stated in META.yml and META.json compared to README and all .pm files

### ISSUE THREAD

**Issue by xtaran** [nohuhu/CGI-Test#8]
Both, `META.yml` and `META.json` state "perl" respectively "perl_5" as license. But that means "Artistic License or GPLv1+" while the boilerplate in all `.pm` files and the README file state that it's (only) under the Artistic License.

Source of this seems to [line 62 of Makefile.PL](https://github.com/nohuhu/CGI-Test/blob/master/Makefile.PL#L62).

Please either change the `README` and all `.pm` files or change `Makefile.PL` to sport the correct license.

**Comment by nohuhu** [comment]
Fixed in https://github.com/nohuhu/CGI-Test/commit/82b4969825c2a7604348564715d8573a70c742ac, thanks for catching!
